// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7cKyaVqbjQ8cwlqOhqhGcj8gNPa498U0',
    appId: '1:855360559505:web:2c05e3fc2b718695a86230',
    messagingSenderId: '855360559505',
    projectId: 'netflix-5fb51',
    authDomain: 'netflix-5fb51.firebaseapp.com',
    storageBucket: 'netflix-5fb51.appspot.com',
    measurementId: 'G-ESQG96PBQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACE-VLvCBftEtHUqjKMPSc_OD2NJzrpFc',
    appId: '1:855360559505:android:3108815a831318b6a86230',
    messagingSenderId: '855360559505',
    projectId: 'netflix-5fb51',
    storageBucket: 'netflix-5fb51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEV2B4mhRp_Cea3FZ6Q957wm-OTaa6J8A',
    appId: '1:855360559505:ios:fe1cb0e217ca33fea86230',
    messagingSenderId: '855360559505',
    projectId: 'netflix-5fb51',
    storageBucket: 'netflix-5fb51.appspot.com',
    iosBundleId: 'com.example.netflixClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEV2B4mhRp_Cea3FZ6Q957wm-OTaa6J8A',
    appId: '1:855360559505:ios:b0d9ab33e6b99f26a86230',
    messagingSenderId: '855360559505',
    projectId: 'netflix-5fb51',
    storageBucket: 'netflix-5fb51.appspot.com',
    iosBundleId: 'com.example.netflixClone.RunnerTests',
  );
}
